name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew jar

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.0.1
      with:
        name: nonametags
        path: ${{github.workspace}}/build/libs
